# Generated by Django 4.2.20 on 2025-03-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_userprofile_user_remove_artist_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='artist_profiles/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='total_listens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
