# Generated by Django 4.2.20 on 2025-03-17 19:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_artist_bio_artist_image_artist_total_listens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='duration',
        ),
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('hiphop', 'Hip-Hop'), ('jazz', 'Jazz'), ('electronic', 'Electronic'), ('classical', 'Classical'), ('rnb', 'R&B'), ('country', 'Country'), ('reggae', 'Reggae'), ('metal', 'Metal')], default='pop', max_length=50),
        ),
        migrations.AddField(
            model_name='track',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
