# Generated by Django 4.2.20 on 2025-03-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_listener_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listener',
            name='name',
        ),
    ]
