# Generated by Django 4.2.20 on 2025-04-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_remove_listener_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(default='covers/default.jpg', upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
